# Generated by Django 5.0.2 on 2024-03-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=300)),
            ],
        ),
    ]
